# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/go-macaron/binding"

[[constraint]]
  branch = "master"
  name = "github.com/go-macaron/session"

[[constraint]]
  branch = "master"
  name = "github.com/go-macaron/toolbox"

[[constraint]]
  branch = "master"
  name = "github.com/influxdata/influxdb1-client"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.3.2"

[[constraint]]
  name = "gopkg.in/macaron.v1"
  version = "1.3.2"

[prune]
  go-tests = true
  unused-packages = true
